ALTER TABLE profil_rw
ADD COLUMN IF NOT EXISTS hero_foto_url TEXT,
ADD COLUMN IF NOT EXISTS nomor_darurat TEXT,
ADD COLUMN IF NOT EXISTS info_penting_kegiatan TEXT,
ADD COLUMN IF NOT EXISTS wa_rw TEXT,
ADD COLUMN IF NOT EXISTS wa_rt1 TEXT,
ADD COLUMN IF NOT EXISTS wa_rt2 TEXT,
ADD COLUMN IF NOT EXISTS wa_rt3 TEXT,
ADD COLUMN IF NOT EXISTS wa_rt4 TEXT;
