ALTER TABLE surat
ADD COLUMN IF NOT EXISTS tujuan VARCHAR(255),
ADD COLUMN IF NOT EXISTS nomor_tiket VARCHAR(50),
ADD COLUMN IF NOT EXISTS pdf_url TEXT,
ADD COLUMN IF NOT EXISTS notif_wa_sent BOOLEAN DEFAULT false;
